name: Trigger Jenkins on Merge

on:
  pull_request:
    types: [closed]

jobs:
  trigger:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins
        run: |
          curl -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            -X POST "${{ secrets.JENKINS_URL }}/job/Postman CICD/build?token=testToken"
